// Generated by scripts/gen-db-types.mjs — do not edit by hand
// Re-run: pnpm db:types:local (or official `pnpm db:types` with Supabase CLI login)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      employees: {
        Row: {
          id: number
          name: string
          role: string
          created_at: string | null
          pin_bcrypt: string | null
        }
        Insert: {
          id?: number
          name: string
          role: string
          created_at?: string | null
          pin_bcrypt?: string | null
        }
        Update: {
          id?: number
          name?: string
          role?: string
          created_at?: string | null
          pin_bcrypt?: string | null
        }
        Relationships: []
      }
      item_ingredients: {
        Row: {
          id: number
          name: string
          quantity: number
          unit: string
          cost: number
          purchase_date: string
          buyer_name: string
          created_at: string
          purchase_order_id: number | null
          price_per_unit: number | null
        }
        Insert: {
          id?: number
          name: string
          quantity: number
          unit: string
          cost: number
          purchase_date?: string
          buyer_name: string
          created_at?: string
          purchase_order_id?: number | null
          price_per_unit?: number | null
        }
        Update: {
          id?: number
          name?: string
          quantity?: number
          unit?: string
          cost?: number
          purchase_date?: string
          buyer_name?: string
          created_at?: string
          purchase_order_id?: number | null
          price_per_unit?: number | null
        }
        Relationships: []
      }
      loyalty_members: {
        Row: {
          phone_number: string
          name: string
          points: number
          created_at: string | null
        }
        Insert: {
          phone_number: string
          name: string
          points?: number
          created_at?: string | null
        }
        Update: {
          phone_number?: string
          name?: string
          points?: number
          created_at?: string | null
        }
        Relationships: []
      }
      menu_items: {
        Row: {
          id: number
          name: string
          price: number
          stock: number
          is_happy_hour: boolean
          happy_hour_price: number | null
          created_at: string | null
          is_stock_tracked: boolean
          category: string
          image_url: string | null
          unit: string
        }
        Insert: {
          id?: number
          name: string
          price: number
          stock?: number
          is_happy_hour?: boolean
          happy_hour_price?: number | null
          created_at?: string | null
          is_stock_tracked?: boolean
          category?: string
          image_url?: string | null
          unit?: string
        }
        Update: {
          id?: number
          name?: string
          price?: number
          stock?: number
          is_happy_hour?: boolean
          happy_hour_price?: number | null
          created_at?: string | null
          is_stock_tracked?: boolean
          category?: string
          image_url?: string | null
          unit?: string
        }
        Relationships: []
      }
      order_item_modifiers: {
        Row: {
          id: number
          order_item_id: number
          modifier_name: string
          extra_price: number
        }
        Insert: {
          id?: number
          order_item_id: number
          modifier_name: string
          extra_price?: number
        }
        Update: {
          id?: number
          order_item_id?: number
          modifier_name?: string
          extra_price?: number
        }
        Relationships: []
      }
      order_items: {
        Row: {
          id: number
          order_id: number
          menu_item_id: number
          quantity: number
          unit_price: number
          status: string
          created_at: string | null
          notes: string | null
        }
        Insert: {
          id?: number
          order_id: number
          menu_item_id: number
          quantity: number
          unit_price: number
          status?: string
          created_at?: string | null
          notes?: string | null
        }
        Update: {
          id?: number
          order_id?: number
          menu_item_id?: number
          quantity?: number
          unit_price?: number
          status?: string
          created_at?: string | null
          notes?: string | null
        }
        Relationships: []
      }
      orders: {
        Row: {
          id: number
          table_id: number
          qr_session_id: string | null
          status: string
          created_at: string | null
        }
        Insert: {
          id?: number
          table_id: number
          qr_session_id?: string | null
          status?: string
          created_at?: string | null
        }
        Update: {
          id?: number
          table_id?: number
          qr_session_id?: string | null
          status?: string
          created_at?: string | null
        }
        Relationships: []
      }
      payment_promotions: {
        Row: {
          id: number
          payment_id: number
          promotion_id: number | null
          promotion_name: string
          promotion_type: string
          discount_value: number
          free_items: Json | null
          created_at: string | null
        }
        Insert: {
          id?: number
          payment_id: number
          promotion_id?: number | null
          promotion_name: string
          promotion_type: string
          discount_value: number
          free_items?: Json | null
          created_at?: string | null
        }
        Update: {
          id?: number
          payment_id?: number
          promotion_id?: number | null
          promotion_name?: string
          promotion_type?: string
          discount_value?: number
          free_items?: Json | null
          created_at?: string | null
        }
        Relationships: []
      }
      payments: {
        Row: {
          id: number
          order_id: number
          payment_method: string
          subtotal: number
          discount_amount: number
          net_amount: number
          points_earned: number
          points_redeemed: number
          created_at: string | null
          phone_number: string | null
          cash_amount: number
          promptpay_amount: number
        }
        Insert: {
          id?: number
          order_id: number
          payment_method: string
          subtotal: number
          discount_amount?: number
          net_amount: number
          points_earned?: number
          points_redeemed?: number
          created_at?: string | null
          phone_number?: string | null
          cash_amount?: number
          promptpay_amount?: number
        }
        Update: {
          id?: number
          order_id?: number
          payment_method?: string
          subtotal?: number
          discount_amount?: number
          net_amount?: number
          points_earned?: number
          points_redeemed?: number
          created_at?: string | null
          phone_number?: string | null
          cash_amount?: number
          promptpay_amount?: number
        }
        Relationships: []
      }
      pin_attempts: {
        Row: {
          client_key: string
          failed_count: number
          locked_until: string | null
          last_failed_at: string
        }
        Insert: {
          client_key: string
          failed_count?: number
          locked_until?: string | null
          last_failed_at?: string
        }
        Update: {
          client_key?: string
          failed_count?: number
          locked_until?: string | null
          last_failed_at?: string
        }
        Relationships: []
      }
      points_logs: {
        Row: {
          id: number
          phone_number: string
          adjustment: number
          reason: string
          adjusted_by: string
          created_at: string | null
        }
        Insert: {
          id?: number
          phone_number: string
          adjustment: number
          reason: string
          adjusted_by: string
          created_at?: string | null
        }
        Update: {
          id?: number
          phone_number?: string
          adjustment?: number
          reason?: string
          adjusted_by?: string
          created_at?: string | null
        }
        Relationships: []
      }
      promotions: {
        Row: {
          id: number
          name: string
          type: string
          discount_percent: number | null
          discount_amount: number | null
          coupon_code: string | null
          buy_qty: number | null
          free_qty: number | null
          min_order_amount: number | null
          is_active: boolean | null
          start_date: string | null
          end_date: string | null
          created_at: string | null
          menu_item_id: number | null
          start_time: string | null
          end_time: string | null
          image_url: string | null
        }
        Insert: {
          id?: number
          name: string
          type: string
          discount_percent?: number | null
          discount_amount?: number | null
          coupon_code?: string | null
          buy_qty?: number | null
          free_qty?: number | null
          min_order_amount?: number | null
          is_active?: boolean | null
          start_date?: string | null
          end_date?: string | null
          created_at?: string | null
          menu_item_id?: number | null
          start_time?: string | null
          end_time?: string | null
          image_url?: string | null
        }
        Update: {
          id?: number
          name?: string
          type?: string
          discount_percent?: number | null
          discount_amount?: number | null
          coupon_code?: string | null
          buy_qty?: number | null
          free_qty?: number | null
          min_order_amount?: number | null
          is_active?: boolean | null
          start_date?: string | null
          end_date?: string | null
          created_at?: string | null
          menu_item_id?: number | null
          start_time?: string | null
          end_time?: string | null
          image_url?: string | null
        }
        Relationships: []
      }
      purchase_orders: {
        Row: {
          id: number
          purchase_date: string
          buyer_name: string
          total_cost: number
          note: string | null
          created_at: string
          created_by_emp_id: number | null
          created_by_name: string | null
        }
        Insert: {
          id?: number
          purchase_date?: string
          buyer_name: string
          total_cost?: number
          note?: string | null
          created_at?: string
          created_by_emp_id?: number | null
          created_by_name?: string | null
        }
        Update: {
          id?: number
          purchase_date?: string
          buyer_name?: string
          total_cost?: number
          note?: string | null
          created_at?: string
          created_by_emp_id?: number | null
          created_by_name?: string | null
        }
        Relationships: []
      }
      qr_sessions: {
        Row: {
          id: string
          table_id: number
          status: string
          created_at: string | null
          expired_at: string | null
        }
        Insert: {
          id?: string
          table_id: number
          status?: string
          created_at?: string | null
          expired_at?: string | null
        }
        Update: {
          id?: string
          table_id?: number
          status?: string
          created_at?: string | null
          expired_at?: string | null
        }
        Relationships: []
      }
      stock_logs: {
        Row: {
          id: number
          menu_item_id: number | null
          menu_item_name: string
          employee_name: string
          old_stock: number
          new_stock: number
          change_amount: number
          created_at: string
        }
        Insert: {
          id?: number
          menu_item_id?: number | null
          menu_item_name: string
          employee_name: string
          old_stock: number
          new_stock: number
          change_amount: number
          created_at?: string
        }
        Update: {
          id?: number
          menu_item_id?: number | null
          menu_item_name?: string
          employee_name?: string
          old_stock?: number
          new_stock?: number
          change_amount?: number
          created_at?: string
        }
        Relationships: []
      }
      tables: {
        Row: {
          id: number
          status: string
          updated_at: string | null
        }
        Insert: {
          id?: number
          status?: string
          updated_at?: string | null
        }
        Update: {
          id?: number
          status?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      void_logs: {
        Row: {
          id: number
          employee_name: string
          menu_name: string
          quantity: number
          total_amount: number
          reason: string
          restored_stock: boolean
          created_at: string | null
          employee_id: number | null
          reason_code: string | null
        }
        Insert: {
          id?: number
          employee_name: string
          menu_name: string
          quantity: number
          total_amount: number
          reason: string
          restored_stock?: boolean
          created_at?: string | null
          employee_id?: number | null
          reason_code?: string | null
        }
        Update: {
          id?: number
          employee_name?: string
          menu_name?: string
          quantity?: number
          total_amount?: number
          reason?: string
          restored_stock?: boolean
          created_at?: string | null
          employee_id?: number | null
          reason_code?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      adjust_loyalty_points: {
        Args: {
          p_phone_number: string | null
          p_adjustment: number | null
          p_reason: string | null
        }
        Returns: Json
      }
      admin_add_employee: {
        Args: {
          p_name: string | null
          p_pin: string | null
          p_role: string | null
        }
        Returns: number
      }
      admin_delete_employee: {
        Args: {
          p_employee_id: number | null
          p_actor_id: number | null
        }
        Returns: string
      }
      admin_list_employees: {
        Args: {}
        Returns: {
            id: number
            name: string
            role: string
            has_pin: boolean
            created_at: string
          }[]
      }
      admin_update_employee: {
        Args: {
          p_employee_id: number | null
          p_name: string | null
          p_pin: string | null
          p_role: string | null
        }
        Returns: string
      }
      complete_checkout: {
        Args: {
          p_order_id: number | null
          p_cash_received: number | null
          p_coupon_code: string | null
          p_phone_number: string | null
          p_points_redeem: number | null
        }
        Returns: {
            status: string
            payment_id: number
            subtotal: number
            promo_discount: number
            points_redeemed: number
            discount_amount: number
            net_amount: number
            points_earned: number
            cash_amount: number
            promptpay_amount: number
            change_amount: number
            payment_method: string
            applied_promos: Json
          }[]
      }
      customer_place_order_batch: {
        Args: {
          p_session_id: string | null
          p_items: Json | null
        }
        Returns: Json
      }
      customer_place_order_item: {
        Args: {
          p_session_id: string | null
          p_menu_item_id: number | null
          p_quantity: number | null
          p_notes: string | null
        }
        Returns: boolean
      }
      is_owner: {
        Args: {}
        Returns: boolean
      }
      is_staff: {
        Args: {}
        Returns: boolean
      }
      jwt_emp_id: {
        Args: {}
        Returns: number
      }
      jwt_emp_name: {
        Args: {}
        Returns: string
      }
      jwt_emp_role: {
        Args: {}
        Returns: string
      }
      menu_item_sale_price: {
        Args: {
          p_is_happy_hour: boolean | null
          p_price: number | null
          p_happy_hour_price: number | null
          p_at: string | null
        }
        Returns: number
      }
      pin_taken: {
        Args: {
          p_pin: string | null
          p_exclude_id: number | null
        }
        Returns: boolean
      }
      place_order_batch: {
        Args: {
          p_table_id: number | null
          p_items: Json | null
        }
        Returns: Json
      }
      place_order_item: {
        Args: {
          p_table_id: number | null
          p_menu_item_id: number | null
          p_quantity: number | null
          p_notes: string | null
        }
        Returns: boolean
      }
      upsert_purchase_order: {
        Args: {
          p_order_id: number | null
          p_purchase_date: string | null
          p_buyer_name: string | null
          p_note: string | null
          p_items: Json | null
        }
        Returns: Json
      }
      verify_pin: {
        Args: {
          p_pin: string | null
          p_client_key: string | null
        }
        Returns: {
            emp_id: number
            emp_name: string
            emp_role: string
            locked_seconds: number
          }[]
      }
      void_order_item: {
        Args: {
          p_order_item_id: number | null
          p_reason_code: string | null
          p_reason_note: string | null
          p_void_quantity: number | null
        }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database[Extract<keyof Database, 'public'>]

export type Tables<
  PublicTableNameOrOptions extends
    | keyof (PublicSchema['Tables'] & PublicSchema['Views'])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions['schema']]['Tables'] &
        Database[PublicTableNameOrOptions['schema']]['Views'])
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions['schema']]['Tables'] &
      Database[PublicTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema['Tables'] & PublicSchema['Views'])
    ? (PublicSchema['Tables'] & PublicSchema['Views'])[PublicTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof PublicSchema['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema['Tables']
    ? PublicSchema['Tables'][PublicTableNameOrOptions] extends { Insert: infer I }
      ? I
      : never
    : never

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof PublicSchema['Tables']
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions['schema']]['Tables']
    : never = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof PublicSchema['Tables']
    ? PublicSchema['Tables'][PublicTableNameOrOptions] extends { Update: infer U }
      ? U
      : never
    : never

export type Enums<
  PublicEnumNameOrOptions extends
    | keyof PublicSchema['Enums']
    | { schema: keyof Database },
  EnumName extends PublicEnumNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicEnumNameOrOptions['schema']]['Enums']
    : never = never,
> = PublicEnumNameOrOptions extends { schema: keyof Database }
  ? Database[PublicEnumNameOrOptions['schema']]['Enums'][EnumName]
  : PublicEnumNameOrOptions extends keyof PublicSchema['Enums']
    ? PublicSchema['Enums'][PublicEnumNameOrOptions]
    : never
